name: Deploy to PROD
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
      - name: Install NodeJs ðŸ”§
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies and build ðŸ“¦
        run: |
          npm install
          npm run build
      - name: Deploy to PROD ðŸš€
        env:
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
          local_dir: 'build/'
          remote_dir: '/home/svetro/'
        run: |
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/gh_actions_key
          chmod 600 ~/.ssh/gh_actions_key
          rsync -avzr --delete -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}
